name: "Test"


on: workflow_dispatch

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Support longpaths
      run: |
        ls /opt/hostedtoolcache/CodeQL/*/x64/codeql/qlpacks/codeql-python
        echo "howdy how" >> /opt/hostedtoolcache/CodeQL/*/x64/codeql/qlpacks/codeql-python/ql/src/Customizations.qll

    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        upload: false
